# Generated by Django 2.2.13 on 2021-01-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210119_2341'),
        ('accounts', '0003_auto_20210119_2042'),
    ]

    operations = [
    ]
