# Generated by Django 2.2.13 on 2020-12-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_skills', to='webapp.ProrgamSkillGoal', verbose_name='Навык'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionskill',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sessionskill',
            name='parent_skill',
        ),
        migrations.RemoveField(
            model_name='sessionskill',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sessionskill',
            name='stimulus',
        ),
    ]
