# Generated by Django 2.2.13 on 2020-12-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_test_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-start_date'], 'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
