# Generated by Django 2.2.13 on 2020-12-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20201221_0650'),
        ('webapp', '0006_auto_20201218_1926'),
    ]

    operations = [
    ]
