# Generated by Django 2.2.13 on 2021-01-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_programskill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prorgamskillgoal',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт'), ('pause', 'Пауза')], default='open', max_length=20, verbose_name='Статус'),
        ),
    ]
